### ISSUE TITLE
Angular.js 1.3 Migration

### ISSUE THREAD

**Issue by lukasziegler** [Anomen/AuthenticationAngularJS#2]
Hi @Anomen and @DanialK, thanks for your great tutorial and 1.0.x and 1.2.x branches so far! I would like to include this approach for authentication into my application using Angular 1.3.10, however I am still struggling with the migration of the promises (public/javascripts/app.js lines 36-51).
Could you also offer a 1.3.10 branch of your project?
Thanks
Lukas

**Comment by Anomen** [comment]
Funny, I just updated my blog to use Angular 1.3.10 two days ago.
I should not be very difficult to adapt in here too.

**Comment by Anomen** [comment]
That's done. You can pull the latest changes in master branch.
I updated the article as well.
